version: '3.5'

services:

  shiptalent_admin:
    container_name: shiptalent_admin
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/usr/src/shiptalent_admin'
      # - '/usr/src/shiptalent_admin/node_modules'
    ports:
      - '3001:3001'
    environment:
      - NODE_ENV=development